services:
    _defaults:
        autowire: true
        autoconfigure: true

    Novactive\Bundle\eZ2FABundle\Command\GenerateUsersGoogleAuthSecretCommand:
        bind:
            $googleAuthenticator: '@scheb_two_factor.security.google_authenticator'


    Novactive\Bundle\eZ2FABundle\Listener\UserEventSubscriber: ~
    Novactive\Bundle\eZ2FABundle\Listener\MenuEventSubscriber: ~

    Novactive\Bundle\eZ2FABundle\Core\SiteAccessAwareQueryExecutor:
        arguments:
            $repositoryConfigurationProvider: "@ezpublish.api.repository_configuration_provider"

    Novactive\Bundle\eZ2FABundle\Security\TwoFactorUserProviderDecorator:
        decorates: 'ezpublish.security.user_provider'

    Novactive\Bundle\eZ2FABundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Novactive\Bundle\eZ2FABundle\Core\QRCodeGenerator: ~