services:
    _defaults:
        autowire: true
        autoconfigure: true

    Novactive\Bundle\eZ2FABundle\Command\Remove2FAForUserCommand: ~

    Novactive\Bundle\eZ2FABundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Novactive\Bundle\eZ2FABundle\Listener\:
        resource: '../../Listener'

    Novactive\Bundle\eZ2FABundle\Core\:
        resource: '../../Core'

    Novactive\Bundle\eZ2FABundle\Core\SiteAccessAwareQueryExecutor:
        arguments:
            $repositoryConfigurationProvider: "@ezpublish.api.repository_configuration_provider"

    Novactive\Bundle\eZ2FABundle\Security\TwoFactorUserProviderDecorator:
        decorates: 'ezpublish.security.user_provider'

    Novactive\Bundle\eZ2FABundle\Security\BackupCodeManager: ~

    Novactive\Bundle\eZ2FABundle\Core\SiteAccessAwareAuthenticatorResolver:
        bind:
            $backupCodesEnabled: '%nova_ez2fa.backup_codes.enabled%'

    Novactive\Bundle\eZ2FABundle\Core\Tab\TwoFAManagement:
        tags:
            - { name: ezplatform.tab, group: location-view }